services:
  - type: web
    name: goponkotha
    env: node
    buildCommand: cd apps/web && bun install && bun run build
    startCommand: cd apps/web && bun run dev
    rootDir: apps/web
    envVars:
      - key: NODE_ENV
        value: production
